### ISSUE TITLE
An exception occurred in telemetry logging.Disabling telemetry to prevent further exceptions.

### ISSUE THREAD

**Issue by ZhenyanSun** [facebookresearch/hyperreel#7]
Dear team，
when I run the code I always meet below error oabout iopath，but after the error the code continue running. I follow the instructions to install the project. Does this matter?
Global seed set to 1
[2023-01-13 09:35:45,172][iopath.common.file_io][ERROR] - An exception occurred in telemetry logging.Disabling telemetry to prevent further exceptions.
Traceback (most recent call last):
  File "/home/zysun/anaconda3/envs/hyperreel/lib/python3.8/site-packages/iopath/common/file_io.py", line 946, in __log_tmetry_keys
    handler.log_event()
  File "/home/zysun/anaconda3/envs/hyperreel/lib/python3.8/site-packages/iopath/common/event_logger.py", line 97, in log_event
    del self._evt
AttributeError: _evt
[2023-01-13 09:35:45,178][iopath.common.file_io][ERROR] - An exception occurred in telemetry logging.Disabling telemetry to prevent further exceptions.
Traceback (most recent call last):
  File "/home/zysun/anaconda3/envs/hyperreel/lib/python3.8/site-packages/iopath/common/file_io.py", line 946, in __log_tmetry_keys
    handler.log_event()
  File "/home/zysun/anaconda3/envs/hyperreel/lib/python3.8/site-packages/iopath/common/event_logger.py", line 97, in log_event
    del self._evt
AttributeError: _evt

**Comment by breuckelen** [comment]
I get this exception as well --- though I've never looked into it, because, as you said, things continue to run normally afterwards. You should be good to go!
